package com.lingxiujz.jz.entity.admin;

import java.util.Date;

public class LxAdminRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role.id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role.role_name
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role.remark
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role.create_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role.create_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String createUserNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role.create_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role.last_update_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role.last_update_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String lastUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role.last_update_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String lastUpdateUserNickname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role.id
     *
     * @return the value of lx_admin_role.id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role.id
     *
     * @param id the value for lx_admin_role.id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role.role_name
     *
     * @return the value of lx_admin_role.role_name
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role.role_name
     *
     * @param roleName the value for lx_admin_role.role_name
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role.remark
     *
     * @return the value of lx_admin_role.remark
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role.remark
     *
     * @param remark the value for lx_admin_role.remark
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role.create_user_id
     *
     * @return the value of lx_admin_role.create_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role.create_user_id
     *
     * @param createUserId the value for lx_admin_role.create_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role.create_user_nickname
     *
     * @return the value of lx_admin_role.create_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getCreateUserNickname() {
        return createUserNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role.create_user_nickname
     *
     * @param createUserNickname the value for lx_admin_role.create_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setCreateUserNickname(String createUserNickname) {
        this.createUserNickname = createUserNickname == null ? null : createUserNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role.create_time
     *
     * @return the value of lx_admin_role.create_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role.create_time
     *
     * @param createTime the value for lx_admin_role.create_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role.last_update_time
     *
     * @return the value of lx_admin_role.last_update_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role.last_update_time
     *
     * @param lastUpdateTime the value for lx_admin_role.last_update_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role.last_update_user_id
     *
     * @return the value of lx_admin_role.last_update_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role.last_update_user_id
     *
     * @param lastUpdateUserId the value for lx_admin_role.last_update_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId == null ? null : lastUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role.last_update_user_nickname
     *
     * @return the value of lx_admin_role.last_update_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getLastUpdateUserNickname() {
        return lastUpdateUserNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role.last_update_user_nickname
     *
     * @param lastUpdateUserNickname the value for lx_admin_role.last_update_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setLastUpdateUserNickname(String lastUpdateUserNickname) {
        this.lastUpdateUserNickname = lastUpdateUserNickname == null ? null : lastUpdateUserNickname.trim();
    }
}