package com.lingxiujz.jz.entity.admin;

import java.util.Date;

public class LxAdminUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.user_name
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String userNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.user_gender
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Integer userGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.user_img
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String userImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.user_birthday
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Date userBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.user_email
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.user_mobile
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.user_status
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Integer userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.user_source
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Integer userSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.remark
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.user_sign
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String userSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.create_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.create_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String createUserNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.last_update_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String lastUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.last_update_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String lastUpdateUserNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.update_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_user_info.create_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.id
     *
     * @return the value of lx_admin_user_info.id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.id
     *
     * @param id the value for lx_admin_user_info.id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.user_name
     *
     * @return the value of lx_admin_user_info.user_name
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.user_name
     *
     * @param userName the value for lx_admin_user_info.user_name
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.user_nickname
     *
     * @return the value of lx_admin_user_info.user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.user_nickname
     *
     * @param userNickname the value for lx_admin_user_info.user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.user_gender
     *
     * @return the value of lx_admin_user_info.user_gender
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Integer getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.user_gender
     *
     * @param userGender the value for lx_admin_user_info.user_gender
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setUserGender(Integer userGender) {
        this.userGender = userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.user_img
     *
     * @return the value of lx_admin_user_info.user_img
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getUserImg() {
        return userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.user_img
     *
     * @param userImg the value for lx_admin_user_info.user_img
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setUserImg(String userImg) {
        this.userImg = userImg == null ? null : userImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.user_birthday
     *
     * @return the value of lx_admin_user_info.user_birthday
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.user_birthday
     *
     * @param userBirthday the value for lx_admin_user_info.user_birthday
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.user_email
     *
     * @return the value of lx_admin_user_info.user_email
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.user_email
     *
     * @param userEmail the value for lx_admin_user_info.user_email
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.user_mobile
     *
     * @return the value of lx_admin_user_info.user_mobile
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.user_mobile
     *
     * @param userMobile the value for lx_admin_user_info.user_mobile
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.user_status
     *
     * @return the value of lx_admin_user_info.user_status
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.user_status
     *
     * @param userStatus the value for lx_admin_user_info.user_status
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.user_source
     *
     * @return the value of lx_admin_user_info.user_source
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Integer getUserSource() {
        return userSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.user_source
     *
     * @param userSource the value for lx_admin_user_info.user_source
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setUserSource(Integer userSource) {
        this.userSource = userSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.remark
     *
     * @return the value of lx_admin_user_info.remark
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.remark
     *
     * @param remark the value for lx_admin_user_info.remark
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.user_sign
     *
     * @return the value of lx_admin_user_info.user_sign
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getUserSign() {
        return userSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.user_sign
     *
     * @param userSign the value for lx_admin_user_info.user_sign
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setUserSign(String userSign) {
        this.userSign = userSign == null ? null : userSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.create_user_id
     *
     * @return the value of lx_admin_user_info.create_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.create_user_id
     *
     * @param createUserId the value for lx_admin_user_info.create_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.create_user_nickname
     *
     * @return the value of lx_admin_user_info.create_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getCreateUserNickname() {
        return createUserNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.create_user_nickname
     *
     * @param createUserNickname the value for lx_admin_user_info.create_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setCreateUserNickname(String createUserNickname) {
        this.createUserNickname = createUserNickname == null ? null : createUserNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.last_update_user_id
     *
     * @return the value of lx_admin_user_info.last_update_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.last_update_user_id
     *
     * @param lastUpdateUserId the value for lx_admin_user_info.last_update_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId == null ? null : lastUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.last_update_user_nickname
     *
     * @return the value of lx_admin_user_info.last_update_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getLastUpdateUserNickname() {
        return lastUpdateUserNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.last_update_user_nickname
     *
     * @param lastUpdateUserNickname the value for lx_admin_user_info.last_update_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setLastUpdateUserNickname(String lastUpdateUserNickname) {
        this.lastUpdateUserNickname = lastUpdateUserNickname == null ? null : lastUpdateUserNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.update_time
     *
     * @return the value of lx_admin_user_info.update_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.update_time
     *
     * @param updateTime the value for lx_admin_user_info.update_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_user_info.create_time
     *
     * @return the value of lx_admin_user_info.create_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_user_info.create_time
     *
     * @param createTime the value for lx_admin_user_info.create_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}