package com.lingxiujz.jz.entity.admin;

import java.util.Date;

public class LxAdminMenus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.is_parent
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Integer isParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.parent_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.parent_name
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String parentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.menu_name
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.menu_href
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String menuHref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.permission
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.menu_level
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Integer menuLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.menu_icon
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String menuIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.menu_sort
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Integer menuSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.menu_status
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Integer menuStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.menu_desc
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String menuDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.create_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.create_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String createUserNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.last_update_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String lastUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.last_update_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String lastUpdateUserNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.last_update_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_menus.create_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.id
     *
     * @return the value of lx_admin_menus.id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.id
     *
     * @param id the value for lx_admin_menus.id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.is_parent
     *
     * @return the value of lx_admin_menus.is_parent
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Integer getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.is_parent
     *
     * @param isParent the value for lx_admin_menus.is_parent
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setIsParent(Integer isParent) {
        this.isParent = isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.parent_id
     *
     * @return the value of lx_admin_menus.parent_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.parent_id
     *
     * @param parentId the value for lx_admin_menus.parent_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.parent_name
     *
     * @return the value of lx_admin_menus.parent_name
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.parent_name
     *
     * @param parentName the value for lx_admin_menus.parent_name
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.menu_name
     *
     * @return the value of lx_admin_menus.menu_name
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.menu_name
     *
     * @param menuName the value for lx_admin_menus.menu_name
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.menu_href
     *
     * @return the value of lx_admin_menus.menu_href
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getMenuHref() {
        return menuHref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.menu_href
     *
     * @param menuHref the value for lx_admin_menus.menu_href
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setMenuHref(String menuHref) {
        this.menuHref = menuHref == null ? null : menuHref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.permission
     *
     * @return the value of lx_admin_menus.permission
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.permission
     *
     * @param permission the value for lx_admin_menus.permission
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.menu_level
     *
     * @return the value of lx_admin_menus.menu_level
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Integer getMenuLevel() {
        return menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.menu_level
     *
     * @param menuLevel the value for lx_admin_menus.menu_level
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setMenuLevel(Integer menuLevel) {
        this.menuLevel = menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.menu_icon
     *
     * @return the value of lx_admin_menus.menu_icon
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.menu_icon
     *
     * @param menuIcon the value for lx_admin_menus.menu_icon
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon == null ? null : menuIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.menu_sort
     *
     * @return the value of lx_admin_menus.menu_sort
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Integer getMenuSort() {
        return menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.menu_sort
     *
     * @param menuSort the value for lx_admin_menus.menu_sort
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setMenuSort(Integer menuSort) {
        this.menuSort = menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.menu_status
     *
     * @return the value of lx_admin_menus.menu_status
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Integer getMenuStatus() {
        return menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.menu_status
     *
     * @param menuStatus the value for lx_admin_menus.menu_status
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setMenuStatus(Integer menuStatus) {
        this.menuStatus = menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.menu_desc
     *
     * @return the value of lx_admin_menus.menu_desc
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.menu_desc
     *
     * @param menuDesc the value for lx_admin_menus.menu_desc
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc == null ? null : menuDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.create_user_id
     *
     * @return the value of lx_admin_menus.create_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.create_user_id
     *
     * @param createUserId the value for lx_admin_menus.create_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.create_user_nickname
     *
     * @return the value of lx_admin_menus.create_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getCreateUserNickname() {
        return createUserNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.create_user_nickname
     *
     * @param createUserNickname the value for lx_admin_menus.create_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setCreateUserNickname(String createUserNickname) {
        this.createUserNickname = createUserNickname == null ? null : createUserNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.last_update_user_id
     *
     * @return the value of lx_admin_menus.last_update_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.last_update_user_id
     *
     * @param lastUpdateUserId the value for lx_admin_menus.last_update_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId == null ? null : lastUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.last_update_user_nickname
     *
     * @return the value of lx_admin_menus.last_update_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getLastUpdateUserNickname() {
        return lastUpdateUserNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.last_update_user_nickname
     *
     * @param lastUpdateUserNickname the value for lx_admin_menus.last_update_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setLastUpdateUserNickname(String lastUpdateUserNickname) {
        this.lastUpdateUserNickname = lastUpdateUserNickname == null ? null : lastUpdateUserNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.last_update_time
     *
     * @return the value of lx_admin_menus.last_update_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.last_update_time
     *
     * @param lastUpdateTime the value for lx_admin_menus.last_update_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_menus.create_time
     *
     * @return the value of lx_admin_menus.create_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_menus.create_time
     *
     * @param createTime the value for lx_admin_menus.create_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}