package com.lingxiujz.jz.entity.admin;

import java.util.Date;

public class LxAdminRoleMenus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role_menus.id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role_menus.role_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role_menus.menu_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role_menus.create_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role_menus.create_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String createUserNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role_menus.last_update_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String lastUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role_menus.last_update_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private String lastUpdateUserNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role_menus.last_update_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lx_admin_role_menus.create_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role_menus.id
     *
     * @return the value of lx_admin_role_menus.id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role_menus.id
     *
     * @param id the value for lx_admin_role_menus.id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role_menus.role_id
     *
     * @return the value of lx_admin_role_menus.role_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role_menus.role_id
     *
     * @param roleId the value for lx_admin_role_menus.role_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role_menus.menu_id
     *
     * @return the value of lx_admin_role_menus.menu_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role_menus.menu_id
     *
     * @param menuId the value for lx_admin_role_menus.menu_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role_menus.create_user_id
     *
     * @return the value of lx_admin_role_menus.create_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role_menus.create_user_id
     *
     * @param createUserId the value for lx_admin_role_menus.create_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role_menus.create_user_nickname
     *
     * @return the value of lx_admin_role_menus.create_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getCreateUserNickname() {
        return createUserNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role_menus.create_user_nickname
     *
     * @param createUserNickname the value for lx_admin_role_menus.create_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setCreateUserNickname(String createUserNickname) {
        this.createUserNickname = createUserNickname == null ? null : createUserNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role_menus.last_update_user_id
     *
     * @return the value of lx_admin_role_menus.last_update_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role_menus.last_update_user_id
     *
     * @param lastUpdateUserId the value for lx_admin_role_menus.last_update_user_id
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId == null ? null : lastUpdateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role_menus.last_update_user_nickname
     *
     * @return the value of lx_admin_role_menus.last_update_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public String getLastUpdateUserNickname() {
        return lastUpdateUserNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role_menus.last_update_user_nickname
     *
     * @param lastUpdateUserNickname the value for lx_admin_role_menus.last_update_user_nickname
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setLastUpdateUserNickname(String lastUpdateUserNickname) {
        this.lastUpdateUserNickname = lastUpdateUserNickname == null ? null : lastUpdateUserNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role_menus.last_update_time
     *
     * @return the value of lx_admin_role_menus.last_update_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role_menus.last_update_time
     *
     * @param lastUpdateTime the value for lx_admin_role_menus.last_update_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lx_admin_role_menus.create_time
     *
     * @return the value of lx_admin_role_menus.create_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lx_admin_role_menus.create_time
     *
     * @param createTime the value for lx_admin_role_menus.create_time
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}