package com.lingxiujz.jz.dao.admin;

import com.lingxiujz.jz.entity.admin.LxAdminRole;
import com.lingxiujz.jz.entity.admin.LxAdminRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LxAdminRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int countByExample(LxAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int deleteByExample(LxAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int insert(LxAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int insertSelective(LxAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    List<LxAdminRole> selectByExample(LxAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    LxAdminRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") LxAdminRole record, @Param("example") LxAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByExample(@Param("record") LxAdminRole record, @Param("example") LxAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByPrimaryKeySelective(LxAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByPrimaryKey(LxAdminRole record);
}