package com.lingxiujz.jz.dao.admin;

import com.lingxiujz.jz.entity.admin.LxAdminMenus;
import com.lingxiujz.jz.entity.admin.LxAdminMenusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LxAdminMenusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int countByExample(LxAdminMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int deleteByExample(LxAdminMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int insert(LxAdminMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int insertSelective(LxAdminMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    List<LxAdminMenus> selectByExample(LxAdminMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    LxAdminMenus selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") LxAdminMenus record, @Param("example") LxAdminMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByExample(@Param("record") LxAdminMenus record, @Param("example") LxAdminMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByPrimaryKeySelective(LxAdminMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByPrimaryKey(LxAdminMenus record);
}