package com.lingxiujz.jz.dao.admin;

import com.lingxiujz.jz.entity.admin.LxAdminUserAuths;
import com.lingxiujz.jz.entity.admin.LxAdminUserAuthsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LxAdminUserAuthsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_user_auths
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int countByExample(LxAdminUserAuthsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_user_auths
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int deleteByExample(LxAdminUserAuthsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_user_auths
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_user_auths
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int insert(LxAdminUserAuths record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_user_auths
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int insertSelective(LxAdminUserAuths record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_user_auths
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    List<LxAdminUserAuths> selectByExample(LxAdminUserAuthsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_user_auths
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    LxAdminUserAuths selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_user_auths
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") LxAdminUserAuths record, @Param("example") LxAdminUserAuthsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_user_auths
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByExample(@Param("record") LxAdminUserAuths record, @Param("example") LxAdminUserAuthsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_user_auths
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByPrimaryKeySelective(LxAdminUserAuths record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_user_auths
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByPrimaryKey(LxAdminUserAuths record);
}