package com.lingxiujz.jz.dao.admin;

import com.lingxiujz.jz.entity.admin.LxAdminRoleMenus;
import com.lingxiujz.jz.entity.admin.LxAdminRoleMenusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LxAdminRoleMenusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int countByExample(LxAdminRoleMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int deleteByExample(LxAdminRoleMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int insert(LxAdminRoleMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int insertSelective(LxAdminRoleMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    List<LxAdminRoleMenus> selectByExample(LxAdminRoleMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    LxAdminRoleMenus selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") LxAdminRoleMenus record, @Param("example") LxAdminRoleMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByExample(@Param("record") LxAdminRoleMenus record, @Param("example") LxAdminRoleMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByPrimaryKeySelective(LxAdminRoleMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lx_admin_role_menus
     *
     * @mbggenerated Tue Apr 16 17:24:27 CST 2019
     */
    int updateByPrimaryKey(LxAdminRoleMenus record);
}